services:
  - type: web
    name: pizzahub
    runtime: python
    rootDir: WebDev-L3-Task1-PizzaDelivery
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt && python seed.py"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: NODE_VERSION
        value: 18.18.0
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./pizza_delivery.db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@pizzahub.com
      - key: ADMIN_PASSWORD
        value: admin123
